version: "3"

services:

  web:
    image: tomcat:7.0
    ports:
      - "8090:8080"
    links:
      - db
      - mq
  db:
    image: mysql:5.6
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 111111

  mq:
    image: rmohr/activemq:5.15.4
    ports:
      - "61616"
      - "8161"
  