---

- name: Copy Hbase 包
  copy:
    src: '{{ srcdir }}/{{ hbase }}'
    dest: /tmp/{{ hbase }}

- unarchive:
    src: '/tmp/{{ hbase }}'
    dest: '{{ appdir }}'
    remote_src: True

- file:
    path: '{{ appdir }}/hbase-1.2.6'
    state: directory
    owner: hadoop
    group: hadoop
    recurse: yes

- name: 复制 hbase-conf 文件夹
  copy:
    src: '{{ hbaseconf }}/{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'backup-masters', dest: '{{ hbasehome }}' }
    - { src: 'hbase-env.sh', dest: '{{ hbasehome }}' }
    - { src: 'hbase-site.xml', dest: '{{ hbasehome }}' }
    - { src: 'regionservers', dest: '{{ hbasehome }}' }

- name: 复制 hadoop 配置文件到 hbase conf文件夹
  copy:
    src: '{{ hadoopconf }}/{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'core-site.xml', dest: '{{ hbasehome }}' }
    - { src: 'hdfs-site.xml', dest: '{{ hbasehome }}' }

- name: Copy profile
  copy:
    src: '{{ srcdir }}/bigdata.sh'
    dest: /etc/profile.d/