# Default values for the chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:

  mq:
    repository: rmohr/activemq
    tag: "5.15.5"
  pullPolicy: IfNotPresent

service:
  name: http
  type: NodePort
  #type: NodePort
  tcpPort: 61616
  webConsolePort: 8161
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    proxy_connect_timeout: 12s #配置点1
    proxy_read_timeout: 10800s
    proxy_send_timeout: 12s
    proxy_set_header: X-Real-IP $remote_addr
    proxy_set_header: X-Forwarded-For $proxy_add_x_forwarded_for
    proxy_set_header: Upgrade $http_upgrade
    proxy_set_header: Connection "upgrade"
  path: /
  hosts:
    - dev.cxzx.fabx.com.cn
    # - cxzx.fabx.com.cn
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
#  limits:
#    cpu: 100m
#    memory: 256Mi
#  requests:
#    cpu: 100m
#    memory: 256Mi

nodeSelector: k8s-master01

tolerations: []

affinity: {}
