---

- name: check jdk variable
  shell: cat /home/{{ ansible_ssh_user }}/.bashrc
  register: bashrc_result

- name: jdk variable configuration ~/.bashrc file
  shell: /bin/echo {{ item }} >> /home/{{ ansible_ssh_user }}/.bashrc; source /home/{{ ansible_ssh_user }}/.bashrc
  when: bashrc_result.stdout.find('JAVA_HOME') == -1
  with_items:
     - export JAVA_HOME=/opt/do/java/jdk1.8.0_77

- name: nifi status
  shell: chdir=/opt/do/hdf/nifi/bin nohup ./nifi.sh stop &
#   register: nifi_status



# - name: sysout status
#   shell: echo 'nifi is running!'
#   when: nifi_status.stdout.find('currently running') != -1

# - name: 复制 nifi.properties
#   copy:
#     src: /home/hdfs/hdfs-site.xml
#     dest: /etc/hadoop/conf/
#     owner: hdfs
#     group: hdfs

# - name: 删除 nifi 临时目录
#   file:
#     path: '/opt/do/hdf/nifi/{{ item.n }}'
#     state: absent
#   with_items:
#     - { n : 'database_repository' }
#     - { n : 'flowfile_repository' }
#     - { n : 'provenance_repository' }

# - name: 删除 nifi 临时目录
#   file:
#     path: /opt/do/hdf/nifi/logs
#     state: absent

# - name: 删除 nifi content_repository 临时目录
#   file:
#     path: /data/nifi-data/content_repository
#     state: absent

# - name: 创建nifi content_repository目录
#   file:
#     path: /data/nifi-data/content_repository
#     state: directory
#     owner: hdfs
#     group: hdfs
#     recurse: yes