#指定storm使用的zk集群
storm.zookeeper.servers:
     - "zookeeper"
#指定storm本地状态保存地址
storm.local.dir: "/data"
#日志
storm.log.dir: "/logs"
#指定storm集群中的nimbus节点所在的服务器
nimbus.host: "nimbus"
#指定nimbus启动JVM最大可用内存大小
nimbus.childopts: "-Xmx1024m"
#指定supervisor启动JVM最大可用内存大小
supervisor.childopts: "-Xmx1024m"
#指定supervisor节点上，每个worker启动JVM最大可用内存大小
worker.childopts: "-Xmx768m"
#指定ui启动JVM最大可用内存大小，ui服务一般与nimbus同在一个节点上。
ui.childopts: "-Xmx768m"
#指定supervisor节点上，启动worker时对应的端口号，每个端口对应槽，每个槽位对应一个worker
supervisor.slots.ports:
    - 6700
    - 6701
    - 6702
    - 6703
