apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  labels:
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        dedicated: master
      tolerations:
        - key: dedicated
          operator: Equal
          value: master
          effect: NoSchedule
      containers:
        - name: nginx
          image: nginx:8.0.51-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: conf-storage
              mountPath: /conf
      volumes:
        - name: conf-storage
---


apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 80
  selector:
    app: nginx
---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: conf-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /root/k8s-study/nginx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s01

---