---
# Source: redis/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: redis
    chart: redis-5.1.3
    heritage: Tiller
    release: redis
  name: redis
data:
  redis.conf: |-
    # User-supplied configuration:
    maxmemory-policy volatile-lru
  master.conf: |-
    dir /bitnami/redis/data
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
  replica.conf: |-
    dir /data
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
