mysqlMaster:
  environment:
    TERM: "xterm"
  command: /usr/bin/supervisord
  image: centos7-mysql56:1.1
  container_name: mysqlMaster
  volumes:
    - ~/opt/src/records:/records
mysqlSlave:
  environment:
    TERM: "xterm"
  command: /usr/bin/supervisord
  image: centos7-mysql56-slave:1.1
  container_name: mysqlSlave
  volumes:
    - ~/opt/src/records:/records
  links:
   - mysqlMaster
mycat1:
  environment:
    TERM: "xterm"
  command: /usr/bin/supervisord -n
  image: mycat:1.2
  container_name: mycat1
  volumes:
    - ~/opt/src/records:/records
  links:
   - mysqlMaster
   - mysqlSlave
asciinemaData:
  privileged: true
  command: /usr/bin/supervisord -n
  image: asciinema:1.1
  container_name: asciinemaData
  volumes:
    - ~/opt/src/records:/records