version: '2'
services:
  zk1:
    ports:
     - "2181:2181"
    command: /usr/bin/sh init.sh
    container_name: zk1
    environment:
      JAVA_HOME: /usr/local/java/jdk1.7.0_79
      MYID: 1
      ZK_HOST1: "192.168.137.11    zk1"
      ZK_HOST2: "192.168.137.22    zk2"
      ZK_HOST3: "192.168.137.33    zk3"
    image: zookeeper-t:1.2
  zk2:
    ports:
     - "2182:2181"
    command: /usr/bin/sh init.sh
    container_name: zk2
    environment:
      JAVA_HOME: /usr/local/java/jdk1.7.0_79
      MYID: 2
      ZK_HOST1: "192.168.137.11    zk1"
      ZK_HOST2: "192.168.137.22    zk2"
      ZK_HOST3: "192.168.137.33    zk3"
    image: zookeeper-t:1.2
  zk3:
    ports:
     - "2183:2181"
    command: /usr/bin/sh init.sh
    container_name: zk3
    environment:
      JAVA_HOME: /usr/local/java/jdk1.7.0_79
      MYID: 3
      ZK_HOST1: "192.168.137.11    zk1"
      ZK_HOST2: "192.168.137.22    zk2"
      ZK_HOST3: "192.168.137.33    zk3"
    image: zookeeper-t:1.2