version: '2'
services:
  zookeeper:
    image: dishui.io:5000/zookeeper:3.4
    container_name: zookeeper
    restart: always
    networks:
      - hadoop
  nimbus:
    image: dishui.io:5000/storm:1.0
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
    volumes:
      - ./conf/storm.yaml:/conf/storm.yaml
    networks:
      - hadoop
  supervisor:
    image: dishui.io:5000/storm:1.0
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always
    volumes:
      - ./conf/storm.yaml:/conf/storm.yaml
    networks:
      - hadoop
  storm-ui:
    image: dishui.io:5000/storm:1.0
    container_name: storm-ui
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./conf/storm.yaml:/conf/storm.yaml
    networks:
      - hadoop
networks:
  hadoop:
    external: true