---
# Source: grafana/templates/clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: grafana
    chart: grafana-1.14.3
    release: grafana
    heritage: Tiller
  name: grafana-clusterrole
rules: []
