---
# Source: grafana/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  labels:
    app: grafana
    chart: grafana-1.14.3
    release: grafana
    heritage: Tiller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.kubernetes.io/ingress.class: nginx
    
spec:
  rules:
    - host: monitor.fabx.com.cn
      http:
        paths:
          - path: /grafana
            backend:
              serviceName: grafana
              servicePort: 80
