---
# Source: grafana/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-1.14.3
    heritage: Tiller
    release: grafana
  name: grafana
