version: "2"

services:
  logstash-file:
    image: dishui.io:5000/logstash:2.4
    container_name: logstash-file
    command: "-f /flow.conf"
    volumes:
      - ./game_logs:/var/game_logs/
      - ./conf/flow-file-to-kafka.conf:/flow.conf
    networks:
      - hadoop
  es:
    image: dishui.io:5000/dishuigit/elastic:1.2
    container_name: es
    ports:
      - "9200:9200"
    networks:
      - hadoop
  logstash-es:
    image: dishui.io:5000/logstash:2.4
    container_name: logstash-es
    command: "-f /flow.conf"
    volumes:
      - ./game_logs:/var/game_logs/
      - ./conf/flow-kafka-to-es.conf:/flow.conf
    networks:
      - hadoop
networks:
  hadoop:
    external: true