version: "2"

services:
  n4:
    image: jzlh.com:5000/nginx:1.10.2
    container_name: n4
    ports:
      - "116.90.81.78:83:80"
    volumes:
      - /root/mount/nginx2/web.conf:/etc/nginx/conf.d/web.conf
      - /root/mount/nginx2/xiaohei.conf:/etc/nginx/conf.d/xiaohei.conf



upstream bmapp {
  server 192.168.1.54:8082;
}
server {
  listen 83;
  server_name   www.xiaoheishifu.com;
  location / {
    proxy_pass http://bmapp/;
  }
  error_page   500 502 503 504 /50x.html;
  location = /50x.html {
    root  /usr/share/nginx/html;
  }
}



server {
  listen 83;
  server_name   www.xiaoheishifu.com;
  location / {
    proxy_pass http://192.168.1.54:8082/;
  }
  error_page   500 502 503 504 /50x.html;
  location = /50x.html {
    root  /usr/share/nginx/html;
  }
}



server {
    listen       80;
    server_name  mailiqing.com www.mailiqing.com;
    fastcgi_intercept_errors on;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://192.168.1.125:8080/;
    }
}