version: '2'
services:
  spark-master:
    image: dishui.io:5000/harisekhon/spark:1.6
    container_name: spark-master
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - hadoop
networks:
  hadoop:
    external: true