version: "2"

services:
  master:
    image: dishui.io:5000/singularities/spark:1.5
    command: start-spark master
    hostname: master
    container_name: spark-master
    ports:
      - "6066:6066"
      - "7070:7070"
      - "8080:8080"
      - "8081:8081"
      - "50070:50070"
    network_mode: "bridge"
  worker:
    image: dishui.io:5000/singularities/spark:1.5
    command: start-spark worker master
    # command: start-spark worker
    container_name: spark-worker
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
    links:
      - master
    network_mode: "bridge"
