---

- name: Copy Scala 包
  copy:
    src: '{{ srcdir }}/{{ scala }}'
    dest: /tmp/{{ scala }}

- unarchive:
    src: '/tmp/{{ scala }}'
    dest: '{{ appdir }}'
    remote_src: True

- file:
    path: '{{ appdir }}/scala-2.10.6'
    state: directory
    owner: hadoop
    group: hadoop
    recurse: yes

- name: Copy profile
  copy:
    src: '{{ srcdir }}/bigdata.sh'
    dest: /etc/profile.d/