---
# Source: nginx-ingress/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-0.28.1
    component: "controller"
    heritage: Tiller
    release: nginx-ingress
  name: nginx-ingress-controller
data:
  enable-vts-status: "false"
