version: '2'
services:
  mysql-s1:
    image: dishui.io:5000/mysql-s1:5.5.52
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    volume_driver: rancher-nfs
    stdin_open: true
    volumes:
    - mysqls1:/data
    tty: true
    links:
    - mysql-m:mysql-m
    labels:
      io.rancher.container.pull_image: always
  mysql-s2:
    image: dishui.io:5000/mysql-s2:5.5.52
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    volume_driver: rancher-nfs
    stdin_open: true
    volumes:
    - mysqls2:/data
    tty: true
    links:
    - mysql-m:mysql-m
    labels:
      io.rancher.container.pull_image: always
  maxscale:
    image: dishui.io:5000/dishuigit/maxscale:1.4
    stdin_open: true
    tty: true
    links:
    - mysql-s2:mysql-s2
    - mysql-s1:mysql-s1
    - mysql-m:mysql-m
    ports:
    - 8003:8003/tcp
    - 4006:4006/tcp
    labels:
      io.rancher.container.pull_image: always
  mysql-m:
    image: dishui.io:5000/mysql-m:5.5.52
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    volume_driver: rancher-nfs
    stdin_open: true
    volumes:
    - mysqlmdata:/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
