version: '2'
volumes:
  maxscale:
    external: true
    driver: rancher-nfs
  mysqlm:
    external: true
    driver: rancher-nfs
  mysqls1:
    external: true
    driver: rancher-nfs
services:
  mysql-s1:
    image: dishui.io:5000/mysql:5.5.52
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    stdin_open: true
    volumes:
    - mysqls1:/mysqls1
    tty: true
    labels:
      io.rancher.container.pull_image: always
  maxscale:
    image: dishui.io:5000/asosso/maxscale:1.4
    stdin_open: true
    volumes:
    - maxscale:/maxscale
    tty: true
    ports:
    - 8003:8003/tcp
    labels:
      io.rancher.container.pull_image: always
  mysql-m:
    image: dishui.io:5000/mysql:5.5.52
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    stdin_open: true
    volumes:
    - mysqlm:/mysqlm
    tty: true
    labels:
      io.rancher.container.pull_image: always
