---
# Source: tomcat/templates/appsrv-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat
    chart: tomcat-0.1.0
    release: tomcat
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
     #nodePort: 
      protocol: TCP
      name: http
  selector:
    app: tomcat
    release: tomcat
