dependencies:
- name: elasticsearch
  version: ^1.10.0
  repository: https://kubernetes-charts.storage.googleapis.com/

- name: logstash
  version: ^1.2.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: logstash.enabled
