version: '2'
services:
  mysql-m:
    image: mailiqing.com:5000/mysql:1.1
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    volume_driver: rancher-nfs
    stdin_open: true
    volumes:
    - mysqls1:/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
  wuliu:
    image: mailiqing.com:5000/mysql:1.1
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    volume_driver: rancher-nfs
    stdin_open: true
    volumes:
    - mysqls2:/data
    tty: true
    links:
    - mysql-m:mysql-m
    labels:
      io.rancher.container.pull_image: always
