---
# Source: prometheus/templates/alertmanager-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.0.3
    component: "alertmanager"
    heritage: Tiller
    release: prometheus
  name: prometheus-alertmanager
