---
# Source: prometheus/templates/alertmanager-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.0.3
    component: "alertmanager"
    heritage: Tiller
    release: prometheus
  name: prometheus-alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 2m
    receivers:
    - name: wechat
      wechat_configs:
      - agent_id: "1000002"
        api_secret: cDSga7jOGMMy5sGzXkMRUiL_sF6GPXt_1X76pAxOaag
        corp_id: ww8369ca55659acbaa
        message: |-
          {{ range .Alerts }}{{ .Annotations.summary }}
          {{ end }}
        to_party: "1"
    route:
      group_by:
      - alertname
      group_interval: 10s
      group_wait: 10s
      receiver: wechat
      repeat_interval: 1h
    