---
# Source: prometheus/templates/alertmanager-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    
  labels:
    app: prometheus
    chart: prometheus-7.0.3
    component: "alertmanager"
    heritage: Tiller
    release: prometheus
  name: prometheus-alertmanager
spec:
  rules:
    - host: monitor.fabx.com.cn
      http:
        paths:
          - path: /alertmanager
            backend:
              serviceName: prometheus-alertmanager
              servicePort: 80