---
# Source: prometheus/templates/pushgateway-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    
  labels:
    app: prometheus
    chart: prometheus-7.0.3
    component: "pushgateway"
    heritage: Tiller
    release: prometheus
  name: prometheus-pushgateway
spec:
  rules:
    - host: monitor.fabx.com.cn
      http:
        paths:
          - path: /pushgateway
            backend:
              serviceName: prometheus-pushgateway
              servicePort: 9091