---
# Source: prometheus/templates/pushgateway-deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.0.3
    component: "pushgateway"
    heritage: Tiller
    release: prometheus
  name: prometheus-pushgateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        component: "pushgateway"
        release: prometheus
    spec:
      serviceAccountName: prometheus-pushgateway
      containers:
        - name: prometheus-pushgateway
          image: "prom/pushgateway:v0.7.0"
          imagePullPolicy: "IfNotPresent"
          args:
            - --web.route-prefix=pushgateway
          ports:
            - containerPort: 9091
          readinessProbe:
            httpGet:
              path: /pushgateway/#/status
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          resources:
            {}
            
