---
# Source: prometheus/templates/pushgateway-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.0.3
    component: "pushgateway"
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus-pushgateway
