---
# Source: prometheus/templates/server-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.0.3
    component: "server"
    heritage: Tiller
    release: RELEASE-NAME
  name: RELEASE-NAME-prometheus-server
spec:
  rules:
    - host: dev.cxzx.fabx.com.cn
      http:
        paths:
          - path: /prometheus
            backend:
              serviceName: RELEASE-NAME-prometheus-server
              servicePort: 80