---
# Source: prometheus/templates/server-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    
  labels:
    app: prometheus
    chart: prometheus-7.0.3
    component: "server"
    heritage: Tiller
    release: prometheus
  name: prometheus-server
spec:
  rules:
    - host: monitor.fabx.com.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus-server
              servicePort: 80