---
# Source: prometheus/templates/server-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-7.0.3
    component: "server"
    heritage: Tiller
    release: prometheus
  name: prometheus-server
