---
# Source: zookeeper/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-zookeeper
  labels:
    app: zookeeper
    chart: zookeeper-1.2.2
    release: RELEASE-NAME
    heritage: Tiller
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: client
      
  selector:
    app: zookeeper
    release: RELEASE-NAME
