# step 1
FROM logstash:2.4-alpine
ADD Shanghai  /etc/localtime
ADD mysql-connector-java-5.1.30.jar  /mysql-connector-java-5.1.30.jar

# docker build -t cxzx.com:5000/logstash:2.4 .
# kubectl run -i --tty logstash --image=cxzx.com:5000/logstash:2.4 bash

