---
# Source: elasticsearch/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch-master
  labels:
    app: elasticsearch
    release: es
    heritage: Tiller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.kubernetes.io/ingress.class: nginx
    
spec:
  rules:
    - host: cxzx.fabx.com.cn
      http:
        paths:
          - path: /es
            backend:
              serviceName: elasticsearch-master
              servicePort: 9200
