version: '2'
services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    restart: always
    ports:
        - "3306:3306"
    environment:
      - MYSQL_USER=azkaban
      - MYSQL_PASSWORD=azkaban
      - MYSQL_DATABASE=azkaban
      - MYSQL_ROOT_PASSWORD=wootwoot
    networks:
      - hadoop
  azkaban-webserver:
    image: puckel/azkaban-webserver
    container_name: azkaban-webserver
    ports:
      - "8443:8443"
    depends_on:
      - mariadb
    networks:
      - hadoop
  azkaban-executor:
    image: puckel/azkaban-executor:my-1.0
    container_name: azkaban-executor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mariadb
    networks:
      - hadoop
networks:
  hadoop:
    external: true