version: '2'
services:
  flume:
    image: dishui.io:5000/lokkju/flume-hdfs
    container_name: flume
    environment:
      # - "FLUME_AGENT_NAME=a1" # netcat
      - "FLUME_AGENT_NAME=agent1"
      - "FLUME_CONF_FILE=/var/tmp/flume.conf"
    volumes:
      # - ./files/flume.conf:/var/tmp/flume.conf #netcat
      # - ./files/flume-dir-hdfs.conf:/var/tmp/flume.conf #dir
      - ./files/flume-file-hdfs.conf:/var/tmp/flume.conf #file
      - ./files/logs:/hadoop/logs #logs
    ports:
      - "44444:44444"
    networks:
      - hadoop
networks:
  hadoop:
    external: true