version: "2"

services:
  hadoop-master:
    image: dishui.io:5000/kiwenlau/hive-on-spark:1.1
    hostname: hadoop-master
    container_name: hadoop-master
    ports:
      - "6066:6066"
      - "7070:7070"
      - "7077:7077"
      - "8080:8080"
      - "8020:8020"
      - "8081:8081"
      - "8088:8088"
      - "50070:50070"
    network_mode: "bridge"
    dns: "172.17.80.3"
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
  hadoop-slave1:
    image: dishui.io:5000/kiwenlau/hive-on-spark:1.1
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    ports:
      - "8042:8042"
    network_mode: "bridge"
    dns: "172.17.80.3"
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh


version: "2"

services:
  hadoop-slave2:
    image: dishui.io:5000/kiwenlau/hive-on-spark:1.1
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    ports:
      - "8042:8042"
    network_mode: "bridge"
    dns: "172.17.80.3"
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
