#cloud-config

hostname: coreos01

coreos:
  etcd2:
    name: "node1"
    initial-advertise-peer-urls: "http://192.168.137.17:2380"
    listen-peer-urls: "http://0.0.0.0:2380"
    listen-client-urls: "http://0.0.0.0:2379,http://127.0.0.1:4001"
    advertise-client-urls: "http://0.0.0.0:2379"
    initial-cluster-token: "etcd-cluster"
    initial-cluster: "node1=http://192.168.137.16:2380,node2=http://192.168.137.17:2380"
    initial-cluster-state: "new"
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
    - name: flanneld.service
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.0.0.0/8","SubnetLen": 20, "SubnetMin": "10.10.0.0","SubnetMax": "10.99.0.0","Backend": { "Type": "udp", "Port": 7890 } }'
      command: start
    - name: "myflanneld.service"
      command: "start"
      content: |
        [Unit]
        Description=Myflanneld Service
        Author=Me
        After=docker.service

        [Service]
        ExecStart=/opt/bin/flanneld

        [Service]
        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.0.0.0/8","SubnetLen": 20, "SubnetMin": "10.10.0.0","SubnetMax": "10.99.0.0","Backend": { "Type": "udp", "Port": 7890 } }'

    - name: "docker.service"
      command: "start"
      content: |
        [Unit]
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.com
        After=containerd.service docker.socket early-docker.target network.target
        Requires=containerd.service docker.socket early-docker.target

        [Service]
        Type=notify
        EnvironmentFile=-/run/flannel/subnet.env
        Environment=DOCKER_OPT_BIP='--bip=${FLANNEL_SUBNET}'
        Environment=DOCKER_OPT_MTU='--mtu=${FLANNEL_MTU}'

        ExecStart=/usr/lib/coreos/dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock $DOCKER_OPTS $DOCKER_CGROUPS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ
        ExecReload=/bin/kill -s HUP $MAINPID
        LimitNOFILE=1048576
        LimitNPROC=infinity
        LimitCORE=infinity
        TasksMax=infinity
        TimeoutStartSec=0
        Delegate=yes

        [Install]
        WantedBy=multi-user.target
    - name: static.network
      content: |
        [Match]
        Name=eno1

        [Network]
        Address=196.168.1.33/24
        Gateway=196.168.1.1
        DNS=114.114.114.114

users:
  - name: core
    ssh-authorized-keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVIo204k9BWPVJCd2zA/3fQmrJLwtDAiolw1Lqh2gOspgqiy5cDNIZSIgFhcIGazPQvGc31yNLbLnnxE9K6PpF7LuZQQsiycNTew+BLXD00enYX8+9QVeqC3sN3ln7gg7AO97eLAHrWMshp0s5wZJVMw4mNBt1XL0cSyFQ4xq4roahtrnVnfZA33RLFKAPO4J/jDP+XLxope259jsW+6q4AJsA9MmtXwPP97fYWkEX4fKhAl0ZVJK3n3t1BKrDa4y2FxBbUxHThhRvsnMXffx3NWkQc8kO0q9Fy9/PkLnDogzHpjyunBbMOqh/VvEy0wPYRz1549osUDVIZonQ3K0T Administrator@WIN-JBJARACQS7U
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDROpatjJDC8mECbuv2v/uuKbhwMWxtedTcpyi42kO2jimcz7pLursYdpiCy8h7+lPkczz9b13MTexApFq23OI2MIe/K2tR+C9Mb2TDsKMcZv9ma1BZLUpWyBcS1KA3bL/U4loHPnmbak9WNvT/gBo1Wdg676kJtyTabXDhQi6Mv8OfmfMiW0AQsRns88osoAoCQGYG8gOi7nJlgXNPjw7VmPS2rU4VBU0mL4vD823OfyWmdBdD1ZCXXlMQmAhY8+PrHJ3V6IDberg3oLa37z8x4/YGeZCid0s19NUH4g5MXlLOcoHhPW5kX7nOqZS15/M+t/sIwAzjNq245hopRD2V dishui@LENOVO-PC
  - groups:
     - sudo
     - docker