#cloud-config

coreos:
  etcd2:
    name: "node1"
    initial-advertise-peer-urls: "http://192.168.137.17:2380"
    listen-peer-urls: "http://0.0.0.0:2380"
    listen-client-urls: "http://0.0.0.0:2379,http://127.0.0.1:4001"
    advertise-client-urls: "http://0.0.0.0:2379"
    initial-cluster-token: "etcd-cluster"
    initial-cluster: "node1=http://192.168.137.16:2380,node2=http://192.168.137.17:2380"
    initial-cluster-state: "new"
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: "myflanneld.service"
      command: "start"
      content: |
        [Unit]
        Description=Myflanneld Service
        Author=Me
        [Service]
        ExecStart=/opt/bin/flanneld --iface="eth1"

        [Service]
        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.0.0.0/8","SubnetLen": 20, "SubnetMin": "10.10.0.0","SubnetMax": "10.99.0.0","Backend": { "Type": "udp", "Port": 7890 } }'
    - name: "docker.service"
      command: "start"
      content: |
        [Unit]
        Description=Docker Application Container Engine
        Documentation=http://docs.docker.com
        After=containerd.service docker.socket early-docker.target network.target myflanneld.service
        Requires=containerd.service docker.socket early-docker.target

        [Service]
        Type=notify
        EnvironmentFile=-/run/flannel/subnet.env

        ExecStart=/usr/lib/coreos/dockerd --host=fd:// --containerd=/var/run/docker/libcontainerd/docker-containerd.sock $DOCKER_OPTS $DOCKER_CGROUPS $DOCKER_OPT_IPMASQ --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}
        ExecReload=/bin/kill -s HUP $MAINPID
        LimitNOFILE=1048576
        LimitNPROC=infinity
        LimitCORE=infinity
        TasksMax=infinity
        TimeoutStartSec=0
        Delegate=yes

        [Install]
        WantedBy=multi-user.target
    - name: settimezone.service
      command: start
      content: |
        [Unit]
        Description=Set the time zone

        [Service]
        ExecStart=/usr/bin/timedatectl set-timezone Asia/Shanghai
        RemainAfterExit=yes
        Type=oneshot
    - name: docker0.service
      command: start
      content: |
        [Unit]
        Description=ifconfig docker0 ${FLANNEL_SUBNET}
        After=docker.service

        [Service]
        EnvironmentFile=-/run/flannel/subnet.env
        ExecStart=/usr/bin/ifconfig docker0 ${FLANNEL_SUBNET}
write_files:
   - path: /etc/hosts
     content: |
        127.0.0.1     localhost
        192.168.137.15    dishui.io
