FROM ubuntu-java-tomcat:1.0
MAINTAINER dishui_git@126.com

RUN locale-gen zh_CN.UTF-8

ENV LANG zh_CN.UTF-8
ENV JAVA_HOME /jdk1.7.0_45
ENV PATH $PATH:$JAVA_HOME/bin
ENV CLASSPATH .:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

RUN apt-get update && apt-get install -y supervisor

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 8080
CMD ["/usr/bin/supervisord"]

