apiVersion: v1
kind: Service
metadata:
  name: {{ include "activemq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "activemq.name" . }}
    helm.sh/chart: {{ include "activemq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.transportPort }}
      protocol: TCP
      name: transport
  selector:
    app.kubernetes.io/name: {{ include "activemq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
