---

- name: 添加HDP仓库
  yum_repository:
    name: HDP
    description: HDP YUM repo
    baseurl: http://10.198.102.122/HDP/centos7/2.6.3.0-235
    gpgcheck: 1
    gpgkey: http://10.198.102.122/HDP/centos7/2.6.3.0-235/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
    enabled: 1
    priority: 1

- name: 添加HDP-Utils仓库
  yum_repository:
    name: HDP-UTILS
    description: HDP-UTILS YUM repo
    baseurl: http://10.198.102.122/HDP-UTILS
    gpgcheck: 1
    gpgkey: http://10.198.102.122/HDP-UTILS/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
    enabled: 1
    priority: 1

- name: 添加自定义仓库
  yum_repository:
    name: pg-msql
    description: pg-msql YUM repo
    baseurl: http://10.198.102.90/pg-msql
    gpgcheck: 0
    enabled: 1

- name: 复制脚本
  copy:
    src: /opt/do/hdf/nifi/bin/msck.sh
    dest: /opt/do/hdf/nifi/bin
    owner: hdfs
    group: hdfs
    mode: 0777

- name: 安装Hadoop client
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - libtirpc-0.2.4-0.10.el7
    - hadoop-client
# - name: 赋予执行权限
#   copy:
#     src: /root/bin/registry-cert.sh
#     dest: /tmp/

# - name: 添加密钥
#   command: sh /tmp/registry-cert.sh

# - name: 拉去rancher镜像
#   command: sh /tmp/pull.sh