---

# - name: 复制 nifi.properties
#   copy:
#     src: /opt/do/hdf/nifi/conf/nifi.properties
#     dest: /opt/do/hdf/nifi/conf/
#     owner: hdfs
#     group: hdfs

# - name: 替换hostname
#   raw: sed -i s@nifi01@`hostname`@ /opt/do/hdf/nifi/conf/nifi.properties

- name: 设置 nifi.cluster.node.read.timeout
  raw: sed -i s@nifi.cluster.node.read.timeout=5@nifi.cluster.node.read.timeout=30@ /opt/do/hdf/nifi/conf/nifi.properties

- name: 设置 nifi.cluster.node.connection.timeout
  raw: sed -i s@nifi.cluster.node.connection.timeout=5@nifi.cluster.node.connection.timeout=30@ /opt/do/hdf/nifi/conf/nifi.properties