#!/usr/bin/env ruby

require 'rubygems' unless defined? Gem

if File.exist?(asciidoctor = (File.expand_path '../../lib/asciidoctor', __FILE__))
  require asciidoctor
else
  require 'asciidoctor'
end
# 解析
require 'asciidoctor-diagram'
require 'asciidoctor/extensions'
require 'asciidoctor/GistBlockMacro'
require 'asciidoctor/gojs'
Asciidoctor::Extensions.register do
    block_macro GistBlockMacro if document.basebackend? 'html'
    block Gojs::BlockProcessor, :gojs
end
#
require 'asciidoctor/cli'

invoker = Asciidoctor::Cli::Invoker.new ARGV
GC.start
invoker.invoke!
exit invoker.code
