---
# Source: activemq/templates/appsrv-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    app: activemq
    chart: activemq-0.1.0
    release: activemq
    heritage: Tiller
spec:
  type: NodePort
  ports:
    - port: 8161
      targetPort: 8161
      nodePort: 31000
      protocol: TCP
      name: tcp
    - port: 61616
      targetPort: 61616
      nodePort: 31100
      protocol: TCP
      name: web-console
  selector:
    app: activemq
    release: activemq
