---
# Source: activemq/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: activemq
  labels:
    app.kubernetes.io/name: activemq
    helm.sh/chart: activemq-0.1.0
    app.kubernetes.io/instance: activemq
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: activemq
      app.kubernetes.io/instance: activemq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: activemq
        app.kubernetes.io/instance: activemq
    spec:
      containers:
        - name: activemq
          image: "rmohr/activemq:5.15.5"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 
            - containerPort: 
          resources:
            {}
            
