---
# Source: activemq/templates/ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: activemq
  labels:
    app.kubernetes.io/name: activemq
    helm.sh/chart: activemq-0.1.0
    app.kubernetes.io/instance: activemq
    app.kubernetes.io/managed-by: Tiller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.kubernetes.io/ingress.class: nginx
    
spec:
  rules:
    - host: "dev.cxzx.fabx.com.cn"
      http:
        paths:
          - path: /mq
            backend:
              serviceName: activemq
              servicePort: 8161
