#! /bin/bash
set -x

BIN_HOME="$(cd "`dirname "$0"`"; pwd)"
source $BIN_HOME/env.sh

if [[ "$@" = *--help ]] || [[ "$@" = *-h ]] || [[ "$#" = 0 ]]; then
  echo "Usage: run-kafka-standalone [start|stop|log]"
  echo -e $pattern
  exit 1
fi



function start(){
  sh $KAFKA_HOME/bin/kafka-server-start.sh -daemon $KAFKA_HOME/config/server.properties
}

function stop(){
  CMD2="$KAFKA_HOME/bin/kafka-server-stop.sh"
  sh $CMD2
}

function status(){
  CMD="source $BIN_HOME/env.sh;jps|grep Kafka"
  # CMD+="if [ ! `ps ax | grep -i 'kafka\.Kafka' | grep java | grep -v grep | awk '{print $1}'` ];then "
  # CMD+="echo \"Kafka Server is bad!\"; "
  # CMD+="else "
  # CMD+="echo \"Kafka Server is ok!\"; "
  # CMD+="fi"
  clush -w $NODES $CMD
}

function log(){
  tail -f $KAFKA_HOME/logs/server.log
}

case $1 in
#
  (start)
  echo "Start Kafka"
  start
  ;;
#
  (stop)
  echo "Stop Kafka"
  stop
  ;;
#
  (status)
  echo "Status Kafka"
  status
  ;;
#
  (log)
  log
  ;;
esac

