version: '2'
services:
  mysql1:
    container_name: mysql1
    image: mailiqing.com/mysql:1.1
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    ports:
     - "3306:3306"
    volumes:
      - ./web-data/mysql5-data:/var/lib/mysql
      - ./web-data:/web-data
      - ./web-data/master-my.cnf:/etc/mysql/conf.d/mysqld.cnf
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
     - ./web.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
    depends_on:
     - web1
  web1:
    command: /usr/bin/supervisord -n
    container_name: web1
    image: mailiqing.com/tomcat:1.1
    volumes:
     - ./web-data/app:/apache-tomcat-7.0.62/webapps/app
     - ./web-data/tmp:/tmp
    links:
     - mysql1
     - es
     - koto