version: '2'
services:
  agent-1:
    image: progrium/consul
    container_name: consul_server
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    command: -server -bootstrap -ui-dir /ui -advertise 192.168.137.16