version: '2'
services:
  dns-server:
    container_name: dns-server
    image: andyshinn/dnsmasq:2.75
    volumes:
      - ./hugo-project:/hugo-project
    ports:
      - "53:53/udp"
      - "53:53/tcp"