version: '2'
services:
  logstash:
    command: /usr/bin/supervisord -n
    container_name: logstash
    image: dishui.io:5000/dishuigit/logstash:1.0
  es:
    container_name: es
    image: dishui.io:5000/dishuigit/elastic:1.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /home/core/opt/src/version2/conf/elasticsearch.yml:/elasticsearch-1.7.1/config/elasticsearch.yml