version: '2'
services:
  gollum:
    privileged: true
    image: dishuigit/gollum:2.0
    container_name: gollum1
    ports:
     - "80:4567"
  plantuml:
    image: dishui.io:5000/dishuigit/plantuml:1.3
    container_name: plantuml
    ports:
     - "8080:8080"
    volumes:
      - /home/core/opt/src/tomcat/plantuml:/apache-tomcat-7.0.47/webapps/plantuml