version: '2'
services:
  logioweb:
    image: 'blacklabelops/logio:0.3.4'
    container_name: logioweb
    environment:
      - 'LOGIO_ADMIN_USER='
      - 'LOGIO_ADMIN_PASSWORD='
      - LOGIO_CERTIFICATE_DNAME=
    ports:
      - '28778:28778'
  harvester:
    image: 'blacklabelops/logio:0.3.4'
    container_name: harvester
    environment:
      - 'DELAYED_START=10'
      - 'LOGIO_HARVESTER_NODENAME=DockerLogs'
      - 'LOGIO_HARVESTER_STREAMNAME=UnifiedLogs'
      - 'LOGIO_HARVESTER_LOGFILES='
      - 'LOGS_DIRECTORIES=/var/lib/docker'
      - 'LOG_FILE_PATTERN=*.log'
    volumes:
      - '/var/lib/docker:/var/lib/docker'
    user: root
    command: harvester


'dishui.io:5000/blacklabelops/logio-rsyslog:1.0'

version: '2'
services:
  logio:
    image: 'dishui.io:5000/blacklabelops/logio:0.3.4'
    container_name: logio
    environment:
      - 'LOGIO_ADMIN_USER='
      - 'LOGIO_ADMIN_PASSWORD='
      - LOGIO_CERTIFICATE_DNAME=
    ports:
      - '28778:28778'
      - '28777:28777'
    command: logio
  harvester:
    image: 'dishui.io:5000/blacklabelops/logio:0.3.4'
    container_name: harvester
    environment:
      - 'DELAYED_START=10'
      - 'LOGIO_HARVESTER_NODENAME=wuliu'
      - 'LOGIO_HARVESTER_STREAMNAME=tomcat'
      - 'LOGIO_HARVESTER_LOGFILES=~/log/tomcat.log ~/log/tomcat-error.log'
    user: root
    command: harvester
  rsyslog:
    image: 'dishui.io:5000/blacklabelops/rsyslog:1.0'
    container_name: rsyslog
    ports:
      - '514:514'
    volumes:
      - './rsyslog.conf:/etc/rsyslog.d/listen.conf'
      - './log:~/log'
    command: rsyslogd



  harvester:
    image: 'dishui.io:5000/blacklabelops/logio:0.3.4'
    container_name: harvester
    user: root
    volumes:
      - './harvester.conf:~/.log.io/harvester.conf'
      - './log:~/log'
    command: harvester



  test-web:
    image: 'wuliu/tomcat:1.3'
    container_name: test-web
    environment:
      - 'SYSLOG_SERVER=196.168.1.33'
      - 'SYSLOG_PORT=514'
      - 'SYSLOG_PROTO=tcp'
    volumes:
      - './harvester.conf:~/.log.io/harvester.conf'
      - './log:~/log'
    ports:
      - '8083:8080'