version: '2'
services:
  maxscale:
    image: dishui.io:5000/asosso/maxscale:1.4
    container_name: maxscale
    volumes:
      - ./maxscale.cnf:/etc/maxscale.d/maxscale.cnf
  mysql-m:
    container_name: mysql-m
    image: dishui.io:5000/mysql-m:5.5.52
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    volumes:
      - ./cnf/mysql/mysql-m.cnf:/etc/mysql/conf.d/mysqld.cnf
  mysql-s1:
    container_name: mysql-s1
    image: dishui.io:5000/mysql:5.5.52
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    volumes:
      - ./cnf/mysql/mysql-s1.cnf:/etc/mysql/conf.d/mysqld.cnf
  mysql-s2:
    container_name: mysql-s2
    image: dishui.io:5000/mysql:5.5.52
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    volumes:
      - ./cnf/mysql/slave2-my.cnf:/etc/mysql/conf.d/mysqld.cnf
