version: '2'
services:
  mysql:
    container_name: mysql
    image: dishui.io:5000/mysql:5.5.55
    environment:
      MYSQL_ROOT_PASSWORD: '111111'
    ports:
      - "3307:3306"
    volumes:
      - /root/dishui/data/mysql-data:/var/lib/mysql
      - /root/dishui/compose/conf/mysql-m.conf:/etc/mysql/conf.d/mysql-m.conf
    networks:
      - hadoop
networks:
  hadoop:
    external: true