version: '2'

services:
  registry-v2:
    image: registry:2.5
    container_name: registry-v2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    volumes:
      - /home/core/registry:/var/lib/registry
      - /home/core/certs:/certs
  registry-web:
    image: dishui.io:5000/konradkleine/docker-registry-frontend:v2
    container_name: registry-web
    ports:
      - "8080:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: dishui.io
      ENV_DOCKER_REGISTRY_PORT: 5000
      ENV_DOCKER_REGISTRY_USE_SSL: 1
    extra_hosts:
      - "dishui.io:192.168.137.15"