---
# Source: elastic-stack/charts/logstash/templates/pipeline-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-stack-logstash-pipeline
  labels:
    app: logstash
    chart: logstash-1.4.1
    release: elastic-stack
    heritage: Tiller
data:
  input_main: |-
    input {
      file {
        path => "/tmp/access_log"
        start_position => "beginning"
      }
    }
  output_main: |-
    output {
      stdout { codec => rubydebug }
      # elasticsearch {
      #   hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
      #   manage_template => false
      #   index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
      #   document_type => "%{[@metadata][type]}"
      # }
    }
